### PR TITLE
Fix/cleanup part 1

### LINKED ISSUE #345: Code cleanup
General code cleanup, to remove unused variables, refactor some code to be consistent with other implementations, rename/move some packages, ...

### PR DESCRIPTION
**Pull request by nils-caspar**
### #345 Code cleanup, part 1 - UI tests and previews
---
#### Summary
- Refactors non-critical parts of the code (i.e. tests, unused variables, documentation, ...)
- The code base is a lot cleaner and more intuitive now, which is more pleasant to work with
### Information for the team.
---
#### Important Changes.
- Refactors:
  - Folder structure for the whole project to make more sense
  - Removes useless files from the bootcamp sample
  - Every UI test now uses a class `UITest` with helper functions for Compose assertions, and better error displaying. Every test in the `ui` package was refactored to use this new class. So, not including `data.model` and `E2ETest`
  - `FirebaseEmulatorsTest` was replaced with `FirebaseTest` and `FirebaseUITest`
  - Test values such as dummy users, reports, passwords, ... were moved to their own objects in `TestConstants`
  - Fake repositories and view-models were moved to tests
  - Moves some previews to tests, removed the vast majority of them due to deprecation
### Information for the reviewer.
---
#### How to test changes.
- Play around with the app and notice that nothing has changed
- For the review process specifically: I really don't recommend using GitHub for it. Checking every file in `ui` tests is a much better solution to see what the code looks like now
#### Implementation details.
- My goal for main was to remove every build warning, so I either handled them properly (in case of unused variables) or suppressed them when adequate (such as unchecked casts in view-model factories)
#### Additional Notes.
- AI assistance was used for some helper functions of `UITest` to make them short and robust
- UI tests now run in half the time, from my testing. This is because I merged a lot of similar tests into one, and I removed some duplicates. The tests could probably run even faster if we can run UI tests before data tests, but that requires changing the package names in main to change their alphabetical order, and that's ugly
- For M4, we could refactor main, tests in `data.model`, add extra tests once that's done for example in UI test because coverage isn't perfect and tests are much easier to implement in there now, check dependencies versions, ...

### CODE REVIEW

File: AgriHealth-Alert-main/app/src/main/java/com/android/agrihealth/MainActivity.kt [hunk 1]
```diff
@@ -138,11 +134,7 @@ class MainActivity : ComponentActivity() {
             Modifier.pointerInput(Unit) { detectTapGestures(onTap = { focusManager.clearFocus() }) }
         // A surface container using the 'background' color from the theme
         Surface(
-            modifier =
-                clearFocusModifier
-                    .fillMaxSize()
-                    .semantics { testTag = C.Tag.main_screen_container }
-                    .navigationBarsPadding(),
+            modifier = clearFocusModifier.fillMaxSize(),
```
Comment (FrancoAdam) [inline AgriHealth-Alert-main/app/src/main/java/com/android/agrihealth/MainActivity.kt:137]: This is the only change I found in main that I thought could cause an issue, but after testing, `navigationBarsPadding()` doesn't seem to do anything anymore.

**Review by FrancoAdam — APPROVED** [review]
👍
