### PR TITLE
Fix report loading and saving logic

### LINKED ISSUE #440: Visit Time Not Refreshed or Saved (ReportView)
There are two bugs I found related to setting visit time feature: 
- After a vet set visit time on planner screen, going back to the ViewReport screen won't refresh the UI.
- When a veterinarian changes the visit time or duration and presses the “+” button to save it, the new values are sometimes not saved (not only UI, it is actually not saved). This seems to appear when a vet FIRST claim the report.

### PR DESCRIPTION
**Pull request by FrancoAdam**
### #440 Fix report loading and saving logic
---
#### Summary
- Fix report in report view not updating properly when setting the date and duration.
- This would be very unpleasant for users if not fixed.
### Information for the reviewer.
---
#### How to test changes.
- Create a report as a farmer and try to reproduce the steps mentioned in the issue.
#### Implementation details.
- forced the report to load if there weren't any changes made in local.

### CODE REVIEW

File: AgriHealth-Alert-main/app/src/main/java/com/android/agrihealth/ui/report/ReportViewViewModel.kt [hunk 1]
```diff
@@ -35,10 +35,10 @@ data class ReportViewUIState(
             farmerId = "FARMER_123",
             officeId = "OFF_456",
             status = ReportStatus.PENDING,
-            answer = null,
+            answer = "null",
```
Comment (FrancoAdam) [inline AgriHealth-Alert-main/app/src/main/java/com/android/agrihealth/ui/report/ReportViewViewModel.kt]: oops

File: AgriHealth-Alert-main/app/src/main/java/com/android/agrihealth/ui/report/ReportViewViewModel.kt [hunk 2]
```diff
@@ -35,10 +35,10 @@ data class ReportViewUIState(
...
             location = Location(46.5191, 6.5668, "Lausanne Farm"),
             assignedVet = "valid_vet_id"),
-    val answerText: String = "",
+    val answerText: String = "I like magoes",
```
Comment (FrancoAdam) [inline AgriHealth-Alert-main/app/src/main/java/com/android/agrihealth/ui/report/ReportViewViewModel.kt]: oops 2

**Review by mekokon5758 — APPROVED** [review]
I took time to check and make sure it works fine, thank you so much for fixing the bug!
