### PR TITLE
Fix save button clearing the picture bug

### LINKED ISSUE #419: Fix ManageOfficeScreen profile picture bug
When you open the ManageOfficeScreen and click the save button without uploading a new picture, the profile picture preview displays the default icon.

### PR DESCRIPTION
**Pull request by mekokon5758**
### #419 Fix save button clearing the picture bug
---
#### Summary
- Fic the bug: on ManageOfficeScreen, not changing the profile picture and clicking the save button clears the profile picuture
### Information for the team.
---
#### Solved issues. (optional)
- #419
### Information for the reviewer.
---
#### How to test changes.
- Login as a vet, go to ManageOfficeScreen, don't change the profile picture and just click "save changes" button. Go back to ProfileScreen. Go to the ManageOfficeScreen again. You should still have your profile picture.
#### Implementation details.
- At first I thought adding the navigation to go back the previous screen will fix this, but it didn't. I'll keep the no navigation for now. I added the PhotoChange enum (kinda like status of the ManageOfficeScreen) to change the behavior of the updateOffice() depend on if the user actually updaetd the picture or not.
#### Additional Notes.
- Tell me if you have an idea of how to write the uppdateOffice() more clean, although this is blocking other Pr so I have to do it quick if there is.

### CODE REVIEW

File: AgriHealth-Alert-main/app/src/main/java/com/android/agrihealth/ui/office/ManageOfficeViewModel.kt [hunk 1]
```diff
@@ -109,11 +117,39 @@ class ManageOfficeViewModel(
...
-        _uiState.value = _uiState.value.copy(uploadedImagePath = uploadedPath, photoUri = null)
+      var uploadedPath = _uiState.value.uploadedImagePath ?: _uiState.value.office?.photoUrl
+
+      Log.d("ManageOfficeViewModel", "uploadedPath: $uploadedPath")
+
+      when (_uiState.value.photoChange) {
+        PhotoChange.UNCHANGED -> {
+          // do nothing — keep existing photoUrl
+          Log.d(
+              "ManageOfficeViewModel",
```
Comment (al23029) [inline AgriHealth-Alert-main/app/src/main/java/com/android/agrihealth/ui/office/ManageOfficeViewModel.kt]: remove the logs im too rushed to go to sleep

Comment (al23029) [reply AgriHealth-Alert-main/app/src/main/java/com/android/agrihealth/ui/office/ManageOfficeViewModel.kt]: ok

**Review by FrancoAdam — APPROVED** [review]
I see you added logic that handles photo removal but currently there is no way to do that, there will be in a PR coming very soon so this is not an issue. Bug is indeed fixed.
